
'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA_DIR=path.join(ROOT,'data'),DB_FILE=path.join(DATA_DIR,'db.json'),UPLOAD_DIR=path.join(ROOT,'uploads');
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify({users:[],sessions:[],resets:[],logs:[],uploads:[]},null,2));
const PORT=Number(process.env.PORT||8080),NODE_ENV=process.env.NODE_ENV||'development';
const ALLOWED=(process.env.ALLOWED_ORIGIN||'*').split(',').map(s=>s.trim());
let writeQueue=Promise.resolve();
function db(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{return{users:[],sessions:[],resets:[],logs:[],uploads:[]}}}
function save(next){writeQueue=writeQueue.then(async()=>{const tmp=DB_FILE+'.tmp';await fs.promises.writeFile(tmp,JSON.stringify(next,null,2));await fs.promises.rename(tmp,DB_FILE)});return writeQueue}
function id(){return crypto.randomUUID()}
function json(res,status,payload,origin){cors(res,origin);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(payload))}
function cors(res,origin){let allow='*';if(ALLOWED[0]!=='*'){allow=ALLOWED.includes(origin)?origin:ALLOWED[0]}res.setHeader('Access-Control-Allow-Origin',allow);res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');res.setHeader('Vary','Origin')}
function readJson(req,max=7*1024*1024){return new Promise((resolve,reject)=>{let n=0,chunks=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Object.assign(new Error('Payload too large'),{status:413}));req.destroy();return}chunks.push(c)});req.on('end',()=>{try{resolve(chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{})}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}))}});req.on('error',reject)})}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return`${salt}:${hash}`}
function verifyPassword(password,stored){const [salt,hex]=String(stored||'').split(':');if(!salt||!hex)return false;const a=Buffer.from(hex,'hex'),b=crypto.scryptSync(password,salt,64);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function newSession(data,userId){const token=crypto.randomBytes(32).toString('base64url');data.sessions.push({token,userId,expiresAt:Date.now()+1000*60*60*24*30});return token}
function userFrom(req,data){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const s=data.sessions.find(x=>x.token===token&&x.expiresAt>Date.now());return s?data.users.find(u=>u.id===s.userId):null}
function publicUser(u){return{username:u.username,email:u.email,profile:u.profile||{}}}
async function sendEmail(to,subject,html){const key=process.env.RESEND_API_KEY,from=process.env.MAIL_FROM;if(!key||!from)return false;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})});return r.ok}
function sanitizeName(s){return String(s||'file').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-100)}
function mimeExt(m){return{'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'}[m]||''}
function serveStatic(req,res){let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p==='/')p='/index.html';const safe=path.normalize(p).replace(/^([.][.][/\\])+/, '');const file=path.join(ROOT,safe);if(!file.startsWith(ROOT))return false;if(!fs.existsSync(file)||!fs.statSync(file).isFile())return false;const ext=path.extname(file).toLowerCase(),type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.gif':'image/gif','.mp4':'video/mp4','.webm':'video/webm','.mov':'video/quicktime','.json':'application/json; charset=utf-8'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res);return true}
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin||'';if(req.method==='OPTIONS'){cors(res,origin);res.writeHead(204);return res.end()}const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api/')){if(serveStatic(req,res))return;res.writeHead(404);return res.end('Not found')}
 try{
  if(url.pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,service:'berry-vibes-ccd'},origin);
  let data=db();data.socialPosts=Array.isArray(data.socialPosts)?data.socialPosts:[];data.socialFollows=Array.isArray(data.socialFollows)?data.socialFollows:[];
  if(url.pathname==='/api/auth/signup'&&req.method==='POST'){const b=await readJson(req),username=String(b.username||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(username.length<3)throw Object.assign(new Error('Username must be at least 3 characters.'),{status:400});if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(new Error('Enter a valid email.'),{status:400});if(password.length<8)throw Object.assign(new Error('Password must be at least 8 characters.'),{status:400});if(data.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))throw Object.assign(new Error('That username is already in use.'),{status:409});if(data.users.some(u=>u.email===email))throw Object.assign(new Error('That email already has an account.'),{status:409});const u={id:id(),username,email,passwordHash:hashPassword(password),createdAt:new Date().toISOString(),profile:{name:username,height:"5'5",heightInches:65,weight:null,reason:'',photo:'',age:25,activity:'',goal:'',onboardingComplete:false}};data.users.push(u);const token=newSession(data,u.id);await save(data);return json(res,201,{token,profile:u.profile,user:publicUser(u)},origin)}
  if(url.pathname==='/api/auth/login'&&req.method==='POST'){const b=await readJson(req),identity=String(b.identity||'').trim().toLowerCase(),u=data.users.find(x=>x.email===identity||x.username.toLowerCase()===identity);if(!u||!verifyPassword(String(b.password||''),u.passwordHash))throw Object.assign(new Error('Invalid username/email or password.'),{status:401});const token=newSession(data,u.id);await save(data);return json(res,200,{token,profile:u.profile,user:publicUser(u)},origin)}
  if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');data.sessions=data.sessions.filter(x=>x.token!==t);await save(data);return json(res,200,{ok:true},origin)}
  if(url.pathname==='/api/auth/forgot-password'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);let devCode;if(u){const code=String(crypto.randomInt(100000,1000000));data.resets=data.resets.filter(x=>x.userId!==u.id);data.resets.push({userId:u.id,codeHash:crypto.createHash('sha256').update(code).digest('hex'),expiresAt:Date.now()+15*60*1000});await save(data);const sent=await sendEmail(email,'Berry Vibes CCD password reset',`<h2>Your reset code is ${code}</h2><p>It expires in 15 minutes.</p>`);if(!sent&&NODE_ENV!=='production')devCode=code}return json(res,200,{ok:true,...(devCode?{devCode}:{})},origin)}
  if(url.pathname==='/api/auth/reset-password'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);if(!u)throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});const h=crypto.createHash('sha256').update(String(b.code||'')).digest('hex'),r=data.resets.find(x=>x.userId===u.id&&x.codeHash===h&&x.expiresAt>Date.now());if(!r)throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});if(String(b.newPassword||'').length<8)throw Object.assign(new Error('New password must be at least 8 characters.'),{status:400});u.passwordHash=hashPassword(String(b.newPassword));data.resets=data.resets.filter(x=>x.userId!==u.id);data.sessions=data.sessions.filter(x=>x.userId!==u.id);await save(data);return json(res,200,{ok:true},origin)}
  if(url.pathname==='/api/auth/forgot-username'&&req.method==='POST'){const b=await readJson(req),email=String(b.email||'').trim().toLowerCase(),u=data.users.find(x=>x.email===email);let devUsername;if(u){const sent=await sendEmail(email,'Your Berry Vibes CCD username',`<h2>Your username is ${u.username}</h2>`);if(!sent&&NODE_ENV!=='production')devUsername=u.username}return json(res,200,{ok:true,...(devUsername?{devUsername}:{})},origin)}
  const user=userFrom(req,data);if(!user)throw Object.assign(new Error('Sign in required.'),{status:401});
  if(url.pathname==='/api/social/bootstrap'&&req.method==='GET'){
    const accepted=(from,to)=>data.socialFollows.some(f=>f.from===from&&f.to===to&&f.status==='accepted');
    const profiles={};
    for(const u of data.users){const social=u.social||{};const allowed=u.id===user.id||social.privacy!=='private'||accepted(user.id,u.id);profiles[u.id]={id:u.id,handle:social.handle||('@'+u.username.toLowerCase().replace(/[^a-z0-9_]/g,'')),name:social.name||u.profile?.name||u.username,bio:allowed?String(social.bio||''):'',privacy:social.privacy==='private'?'private':'public',photo:String(social.photo||u.profile?.photo||''),location:allowed?String(social.location||''):''}}
    const posts=data.socialPosts.filter(p=>{if(p.authorId===user.id)return true;const author=data.users.find(u=>u.id===p.authorId),privacy=author?.social?.privacy==='private'?'private':'public';if(privacy==='private'&&!accepted(user.id,p.authorId))return false;return p.visibility==='public'||(p.visibility==='followers'&&accepted(user.id,p.authorId))}).map(p=>({...p}));
    const follows=data.socialFollows.filter(f=>f.status==='accepted'||f.from===user.id||f.to===user.id).map(f=>({...f}));
    return json(res,200,{meId:user.id,social:{profiles,posts,follows}},origin)
  }
  if(url.pathname==='/api/social/sync'&&req.method==='POST'){
    const b=await readJson(req,2*1024*1024),client=b.social&&typeof b.social==='object'?b.social:{profiles:{},posts:[],follows:[]},cp=client.profiles?.[user.id]||{};
    user.social={...(user.social||{}),handle:String(cp.handle||user.social?.handle||('@'+user.username)).slice(0,40),name:String(cp.name||user.profile?.name||user.username).slice(0,80),bio:String(cp.bio||'').slice(0,300),privacy:cp.privacy==='private'?'private':'public',photo:String(cp.photo||user.profile?.photo||'').slice(0,5000),location:String(cp.location||'').slice(0,100)};
    const ownClient=(Array.isArray(client.posts)?client.posts:[]).filter(p=>p.authorId===user.id),ownIds=new Set(ownClient.map(p=>String(p.id)));
    data.socialPosts=data.socialPosts.filter(p=>p.authorId!==user.id||ownIds.has(String(p.id)));
    for(const p of ownClient){let row=data.socialPosts.find(x=>String(x.id)===String(p.id)&&x.authorId===user.id);if(!row){row={id:String(p.id||id()),authorId:user.id,text:'',photo:'',media:[],visibility:'public',createdAt:p.createdAt||new Date().toISOString(),likes:[],comments:[],shares:0};data.socialPosts.push(row)}row.text=String(p.text||'').slice(0,1200);row.photo=String(p.photo||'').slice(0,10000000);row.media=(Array.isArray(p.media)?p.media:[]).slice(0,4).map(m=>({url:String(m?.url||'').slice(0,10000000),type:m?.type==='video'?'video':'image',mime:String(m?.mime||'').slice(0,80),name:String(m?.name||'media').slice(0,120)}));row.visibility=['public','followers','private'].includes(p.visibility)?p.visibility:'public'}
    for(const cpst of (Array.isArray(client.posts)?client.posts:[])){const row=data.socialPosts.find(x=>String(x.id)===String(cpst.id));if(!row)continue;row.likes=Array.isArray(row.likes)?row.likes:[];const clientLikes=Array.isArray(cpst.likes)?cpst.likes:[];const liked=clientLikes.includes(user.id);row.likes=row.likes.filter(x=>x!==user.id);if(liked)row.likes.push(user.id);row.comments=Array.isArray(row.comments)?row.comments:[];for(const c of (Array.isArray(cpst.comments)?cpst.comments:[]).filter(c=>c.userId===user.id)){if(!row.comments.some(x=>String(x.id)===String(c.id)))row.comments.push({id:String(c.id||id()),userId:user.id,userName:String(c.userName||user.social?.name||user.username).slice(0,80),text:String(c.text||'').slice(0,500),createdAt:c.createdAt||new Date().toISOString()})}row.shares=Math.max(Number(row.shares)||0,Number(cpst.shares)||0)}
    const clientOut=(Array.isArray(client.follows)?client.follows:[]).filter(f=>f.from===user.id);data.socialFollows=data.socialFollows.filter(f=>f.from!==user.id);for(const f of clientOut){if(data.users.some(u=>u.id===f.to))data.socialFollows.push({from:user.id,to:f.to,status:f.status==='pending'?'pending':'accepted'})}
    const clientIncoming=(Array.isArray(client.follows)?client.follows:[]).filter(f=>f.to===user.id);data.socialFollows=data.socialFollows.filter(f=>f.to!==user.id||clientIncoming.some(cf=>cf.from===f.from&&cf.to===user.id));for(const existing of data.socialFollows.filter(f=>f.to===user.id)){const cf=clientIncoming.find(f=>f.from===existing.from);if(cf&&cf.status==='accepted')existing.status='accepted'}
    await save(data);return json(res,200,{ok:true},origin)
  }
  if(url.pathname==='/api/account/data'&&req.method==='DELETE'){
    const userId=user.id,uploadRows=(data.uploads||[]).filter(x=>x.userId===userId);
    for(const u of uploadRows){try{const file=path.join(ROOT,String(u.url||'').replace(/^\//,''));if(file.startsWith(UPLOAD_DIR)&&fs.existsSync(file))await fs.promises.unlink(file)}catch{}}
    data.logs=(data.logs||[]).filter(x=>x.userId!==userId);data.uploads=(data.uploads||[]).filter(x=>x.userId!==userId);data.socialPosts=(data.socialPosts||[]).filter(x=>x.authorId!==userId);data.socialFollows=(data.socialFollows||[]).filter(x=>x.from!==userId&&x.to!==userId);data.resets=(data.resets||[]).filter(x=>x.userId!==userId);user.social=undefined;user.profile={name:user.username,height:"5'5",heightInches:65,weight:null,reason:'',photo:'',age:25,activity:'',goal:'',onboardingComplete:false};await save(data);return json(res,200,{ok:true,profile:user.profile},origin)
  }
  if(url.pathname==='/api/account'&&req.method==='DELETE'){
    const userId=user.id,uploadRows=(data.uploads||[]).filter(x=>x.userId===userId);
    for(const u of uploadRows){try{const file=path.join(ROOT,String(u.url||'').replace(/^\//,''));if(file.startsWith(UPLOAD_DIR)&&fs.existsSync(file))await fs.promises.unlink(file)}catch{}}
    data.users=(data.users||[]).filter(x=>x.id!==userId);data.sessions=(data.sessions||[]).filter(x=>x.userId!==userId);data.resets=(data.resets||[]).filter(x=>x.userId!==userId);data.logs=(data.logs||[]).filter(x=>x.userId!==userId);data.uploads=(data.uploads||[]).filter(x=>x.userId!==userId);data.socialPosts=(data.socialPosts||[]).filter(x=>x.authorId!==userId);data.socialFollows=(data.socialFollows||[]).filter(x=>x.from!==userId&&x.to!==userId);await save(data);return json(res,200,{ok:true},origin)
  }
  if(url.pathname==='/api/me'&&req.method==='GET')return json(res,200,{user:publicUser(user),profile:user.profile||{}},origin);
  if(url.pathname==='/api/profile'&&req.method==='GET')return json(res,200,{profile:user.profile||{}},origin);
  if(url.pathname==='/api/profile'&&req.method==='PUT'){const b=await readJson(req);user.profile={...(user.profile||{}),name:String(b.name||user.username).slice(0,80),height:String(b.height||user.profile?.height||"5'5").slice(0,20),heightInches:Number(b.heightInches)||Number(user.profile?.heightInches)||65,weight:(b.weight===''||b.weight==null)?null:Number(b.weight)||null,reason:String(b.reason||'').slice(0,1000),photo:String(b.photo||'').slice(0,5000),age:Number(b.age)||Number(user.profile?.age)||25,activity:String(b.activity||user.profile?.activity||'').slice(0,100),goal:String(b.goal||user.profile?.goal||'').slice(0,160),onboardingComplete:!!(b.onboardingComplete??user.profile?.onboardingComplete)};await save(data);return json(res,200,{profile:user.profile},origin)}
  if(url.pathname==='/api/logs'&&req.method==='GET'){return json(res,200,{logs:data.logs.filter(x=>x.userId===user.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,1000)},origin)}
  if(url.pathname==='/api/logs'&&req.method==='POST'){const b=await readJson(req,512*1024);const row={id:id(),userId:user.id,createdAt:new Date().toISOString(),...b};delete row.userId;row.userId=user.id;data.logs.push(row);await save(data);return json(res,201,{log:row},origin)}
  if(url.pathname.startsWith('/api/logs/')&&req.method==='PUT'){const logId=decodeURIComponent(url.pathname.slice('/api/logs/'.length)),i=data.logs.findIndex(x=>x.id===logId&&x.userId===user.id);if(i<0)throw Object.assign(new Error('Log not found.'),{status:404});const b=await readJson(req,512*1024);data.logs[i]={...data.logs[i],...b,id:logId,userId:user.id,updatedAt:new Date().toISOString()};await save(data);return json(res,200,{log:data.logs[i]},origin)}
  if(url.pathname.startsWith('/api/logs/')&&req.method==='DELETE'){const logId=decodeURIComponent(url.pathname.slice('/api/logs/'.length)),before=data.logs.length;data.logs=data.logs.filter(x=>!(x.id===logId&&x.userId===user.id));if(data.logs.length===before)throw Object.assign(new Error('Log not found.'),{status:404});await save(data);return json(res,200,{ok:true},origin)}
  if(url.pathname==='/api/upload'&&req.method==='POST'){const b=await readJson(req,30*1024*1024),m=String(b.mime||''),ext=mimeExt(m);if(!ext)throw Object.assign(new Error('Upload a JPG, PNG, WEBP, GIF, MP4, WEBM, or MOV file.'),{status:400});const match=String(b.dataUrl||'').match(/^data:(?:image\/(?:jpeg|png|webp|gif)|video\/(?:mp4|webm|quicktime));base64,(.+)$/);if(!match)throw Object.assign(new Error('Invalid media data.'),{status:400});const buf=Buffer.from(match[1],'base64');if(buf.length>20*1024*1024)throw Object.assign(new Error('Media must be 20 MB or smaller.'),{status:413});const name=`${user.id.slice(0,8)}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;await fs.promises.writeFile(path.join(UPLOAD_DIR,name),buf);const row={id:id(),userId:user.id,name:sanitizeName(b.name),kind:String(b.kind||'media').slice(0,40),mime:m,url:`/uploads/${name}`,createdAt:new Date().toISOString()};data.uploads.push(row);await save(data);return json(res,201,{url:row.url,upload:row},origin)}
  return json(res,404,{error:'API route not found.'},origin)
 }catch(err){return json(res,err.status||500,{error:err.status?err.message:'Server error.'},origin)}
});
server.listen(PORT,()=>console.log(`Berry Vibes CCD server running on http://localhost:${PORT}`));
